'use client';
import {useEffect,useState} from 'react';
import {motion} from 'framer-motion';
import {Search,MapPin,Wind,Eye,Gauge,Sunrise,Sunset,LoaderCircle,LocateFixed,CloudSun} from 'lucide-react';
type Weather={location:{name:string;country:string;admin?:string};current:any;daily:any;timezone:string};
const icon=(c:number)=>c===0?'☀':c<=3?'⛅':c<=48?'☁':c<=67?'🌧':c<=77?'❄':c<=82?'🌦':'⛈';
export default function Home(){const [city,setCity]=useState('Pune');const [data,setData]=useState<Weather|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
const load=async(q=city)=>{if(!q.trim())return;setLoading(true);setError('');try{const r=await fetch('/api/weather?city='+encodeURIComponent(q));const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j);setCity(j.location.name)}catch(e:any){setError(e.message||'Could not load weather.')}finally{setLoading(false)}};
useEffect(()=>{load('Pune')},[]);
const locate=()=>{if(!navigator.geolocation){setError('Location is not supported by this browser.');return}setLoading(true);navigator.geolocation.getCurrentPosition(async p=>{try{const r=await fetch('/api/weather?city='+encodeURIComponent(p.coords.latitude+','+p.coords.longitude));const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j);setCity(j.location.name)}catch{setError('Could not use your current location.')}finally{setLoading(false)}},()=>{setLoading(false);setError('Location permission was denied.')})};
return <main className="min-h-screen overflow-hidden"><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 sm:py-12"><header className="mb-10 flex items-center justify-between"><div className="flex items-center gap-2 font-bold text-xl"><CloudSun className="text-sky-300"/>Skycast</div><button onClick={locate} className="glass flex items-center gap-2 rounded-full px-4 py-2 text-sm text-slate-200 hover:bg-white/10"><LocateFixed size={16}/>Use my location</button></header>
<section className="mb-8 max-w-3xl"><p className="mb-3 text-sm font-semibold uppercase tracking-[.2em] text-sky-300">Weather, without the noise.</p><h1 className="text-4xl font-bold tracking-tight sm:text-6xl">Know what the day feels like before you step outside.</h1><p className="mt-4 text-slate-400 sm:text-lg">Simple, accurate weather at a glance — current conditions, the week ahead, and the details that matter.</p></section>
<form onSubmit={e=>{e.preventDefault();load()}} className="glass mb-8 flex max-w-3xl items-center gap-3 rounded-2xl p-2"><Search className="ml-3 text-slate-500" size={20}/><input aria-label="Search city" value={city} onChange={e=>setCity(e.target.value)} placeholder="Search city or location" className="min-w-0 flex-1 bg-transparent px-1 py-3 outline-none placeholder:text-slate-500"/><button disabled={loading} className="rounded-xl bg-sky-300 px-5 py-3 font-semibold text-slate-950 hover:bg-sky-200 disabled:opacity-60">{loading?<LoaderCircle className="animate-spin" size={18}/>: 'Search'}</button></form>
{error&&<div role="alert" className="mb-6 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-red-200">{error}</div>}
{data?<><motion.section initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="glass rounded-3xl p-6 sm:p-8"><div className="flex flex-col gap-8 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2 text-slate-300"><MapPin size={18}/>{data.location.name}, {data.location.country}</div><div className="mt-5 flex items-center gap-5"><span className="text-7xl font-bold tracking-tight">{Math.round(data.current.temperature_2m)}°</span><span className="text-6xl">{icon(data.current.weather_code)}</span></div><p className="mt-2 text-xl text-slate-200">{data.current.condition}</p><p className="mt-1 text-slate-400">Feels like {Math.round(data.current.apparent_temperature)}°</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 md:max-w-xl">{[[Wind,'Wind',data.current.wind_speed_10m+' km/h'],[Gauge,'Pressure',Math.round(data.current.surface_pressure)+' hPa'],[Eye,'Visibility',Math.round(data.current.visibility/1000)+' km'],[CloudSun,'Humidity',data.current.relative_humidity_2m+'%']].map(([I,l,v]:any)=><div key={l} className="rounded-2xl bg-white/[.04] p-4"><I size={17} className="text-sky-300"/><p className="mt-3 text-xs text-slate-500">{l}</p><p className="mt-1 font-semibold">{v}</p></div>)}</div></div></motion.section>
<section className="mt-8"><div className="mb-4 flex items-end justify-between"><h2 className="text-2xl font-bold">7-day forecast</h2><span className="text-sm text-slate-500">{data.timezone}</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{data.daily.time.map((d:string,i:number)=><motion.div whileHover={{y:-3}} key={d} className="glass rounded-2xl p-4"><p className="text-sm text-slate-400">{i===0?'Today':new Date(d+'T12:00:00').toLocaleDateString('en',{weekday:'short'})}</p><div className="my-5 text-3xl">{icon(data.daily.weather_code[i])}</div><p className="font-semibold">{Math.round(data.daily.temperature_2m_max[i])}° <span className="font-normal text-slate-500">{Math.round(data.daily.temperature_2m_min[i])}°</span></p></motion.div>)}</div></section>
<section className="mt-8 grid gap-3 sm:grid-cols-2"><div className="glass flex items-center gap-4 rounded-2xl p-5"><Sunrise className="text-amber-300"/><div><p className="text-xs text-slate-500">Sunrise</p><p className="font-semibold">{new Date(data.daily.sunrise[0]).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</p></div></div><div className="glass flex items-center gap-4 rounded-2xl p-5"><Sunset className="text-orange-300"/><div><p className="text-xs text-slate-500">Sunset</p><p className="font-semibold">{new Date(data.daily.sunset[0]).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</p></div></div></section></>:!loading&&!error&&<div className="glass rounded-3xl p-10 text-center text-slate-400">Search for a city to see its weather.</div>}
<footer className="mt-12 text-sm text-slate-600">Open → search → understand → plan.</footer></div></main>}